-- MySQL Script generated by MySQL Workbench
-- mié 18 may 2016 21:32:22 CLT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`humo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`humo` (
  `id_humo` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(50) NOT NULL COMMENT 'Registros obtenidos desde sensor de humo',
  PRIMARY KEY (`id_humo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`temperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`temperatura` (
  `id_temperatura` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_temperatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimiento` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_movimiento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
